def v1enc(text):
	text = text.lower()
	text = text.replace("a", "aaaaa ")
	text = text.replace("b", "aaaab ")
	text = text.replace("c", "aaaba ")
	text = text.replace("d", "aaabb ")
	text = text.replace("e", "aabaa ")
	text = text.replace("f", "aabab ")
	text = text.replace("g", "aabba ")
	text = text.replace("h", "aabbb ")
	text = text.replace("i", "abaaa ") #i and j are the same in version 1
	text = text.replace("j", "abaaa ") #i and j are the same in version 1
	text = text.replace("k", "abaab ")
	text = text.replace("l", "ababa ")
	text = text.replace("m", "ababb ")
	text = text.replace("n", "abbaa ")
	text = text.replace("o", "abbab ")
	text = text.replace("p", "abbba ")
	text = text.replace("q", "abbbb ")
	text = text.replace("r", "baaaa ")
	text = text.replace("s", "baaab ")
	text = text.replace("t", "baaba ")
	text = text.replace("u", "baabb ") #u and v are the same in version 1
	text = text.replace("v", "baabb ") #u and v are the same in version 1
	text = text.replace("w", "babaa ")
	text = text.replace("x", "babab ")
	text = text.replace("y", "babba ")
	text = text.replace("z", "babbb ")
	return text

def v1dec(text):
	text = text.lower()
	text = text.replace("aaaaa", "a")
	text = text.replace("aaaab", "b")
	text = text.replace("aaaba", "c")
	text = text.replace("aaabb", "d")
	text = text.replace("aabaa", "e")
	text = text.replace("aabab", "f")
	text = text.replace("aabba", "g")
	text = text.replace("aabbb", "h")
	text = text.replace("abaaa", "[i/j]") #i and j are the same in version 1
	text = text.replace("abaaa", "[i/j]") #i and j are the same in version 1
	text = text.replace("abaab", "k")
	text = text.replace("ababa", "l")
	text = text.replace("ababb", "m")
	text = text.replace("abbaa", "n")
	text = text.replace("abbab", "o")
	text = text.replace("abbba", "p")
	text = text.replace("abbbb", "q")
	text = text.replace("baaaa", "r")
	text = text.replace("baaab", "s")
	text = text.replace("baaba", "t")
	text = text.replace("baabb", "[u/v]") #u and v are the same in version 1
	text = text.replace("baabb", "[u/v]") #u and v are the same in version 1
	text = text.replace("babaa", "w")
	text = text.replace("babab", "x")
	text = text.replace("babba", "y")
	text = text.replace("babbb", "z")
	return text


def v2enc(text):
        text = text.lower()
        text = text.replace("a", "aaaaa ")
        text = text.replace("b", "aaaab ")
        text = text.replace("c", "aaaba ")
        text = text.replace("d", "aaabb ")
        text = text.replace("e", "aabaa ")
        text = text.replace("f", "aabab ")
        text = text.replace("g", "aabba ")
        text = text.replace("h", "aabbb ")
        text = text.replace("i", "abaaa ")
        text = text.replace("j", "abaab ")
        text = text.replace("k", "ababa ")
        text = text.replace("l", "ababb ")
        text = text.replace("m", "abbaa ")
        text = text.replace("n", "abbab ")
        text = text.replace("o", "abbba ")
        text = text.replace("p", "abbbb ")
        text = text.replace("q", "baaaa ")
        text = text.replace("r", "baaab ")
        text = text.replace("s", "baaba ")
        text = text.replace("t", "baabb ")
        text = text.replace("u", "babaa ")
        text = text.replace("v", "babab ")
        text = text.replace("w", "babba ")
        text = text.replace("x", "babbb ")
        text = text.replace("y", "bbaaa ")
        text = text.replace("z", "bbaab ")
        return text

def v2dec(text):
        text = text.lower()
        text = text.replace("aaaaa", "a")
        text = text.replace("aaaab", "b")
        text = text.replace("aaaba", "c")
        text = text.replace("aaabb", "d")
        text = text.replace("aabaa", "e")
        text = text.replace("aabab", "f")
        text = text.replace("aabba", "g")
        text = text.replace("aabbb", "h")
        text = text.replace("abaaa", "i")
        text = text.replace("abaab", "j")
        text = text.replace("ababa", "k")
        text = text.replace("ababb", "l")
        text = text.replace("abbaa", "m")
        text = text.replace("abbab", "n")
        text = text.replace("abbba", "o")
        text = text.replace("abbbb", "p")
        text = text.replace("baaaa", "q")
        text = text.replace("baaab", "r")
        text = text.replace("baaba", "s")
        text = text.replace("baabb", "t")
        text = text.replace("babaa", "u")
        text = text.replace("babab", "v")
        text = text.replace("babba", "w")
        text = text.replace("babbb", "x")
        text = text.replace("bbaaa", "y")
        text = text.replace("bbaab", "z")
        return text
