import random

choice = [
"Peter Montgomery",
"Jeffrey Yedinak",
"Bruce Fairfield",
"Brian Tarry",
"Roy Janson",
"Joshua Sprague",
"Steven Natale",
"Bruce Hogans",
"James Castle",
"Brian Jenkins",
"Michael Abbott",
"John Gibson",
"Ronald Smith",
"William Packard",
"Nicholas Ray",
"Miguel Nielson",
"Clarence Renfrow",
"Richard Bryant",
"Johnny O'Donnell",
"William Hoover",
"James Ruffin",
"Richard Crain",
"Victor Dean",
"Jeffrey Barker",
"Lance Hicks",
"Roy Busby",
"Kevin Underwood",
"Lloyd Turner",
"Todd Wilkerson",
"Ignacio Evans",
"Charles Hill",
"Hung Corn",
"William Drye",
"Charlie Garner",
"Anthony Moulton",
"Charles Cover",
"Joseph Styles",
"Patrick Bowers",
"Gerardo Robert",
"Christopher Hawkins",
"Vince Gould",
"Sam Louis",
"Melvin Walsh",
"Byron Lamb",
"Jared Harper",
"Tony Mannin",
"Pete Barrera",
"Johnny Harding",
"Ryan Warren",
"Raymond Hopkins",
"Lee Conley",
"Bobby Meyers",
"Harvey Adams",
"Brett Russell",
"Randy Booker",
"Billy Curry",
"Dan Crane",
"Marshall Woodward",
"Kenneth Olsen",
"Sean Hamilton",
"Howard Wilkinson",
"Adrian Harman",
"Danny McDonald",
"Hubert Morgan",
"Carlos McCall",
"Lonnie McCullough",
"Loren Owens",
"Eduardo Christian",
"Roderick Metcalf",
"Lucas Arnold",
"Julius Dean",
"Eric Hull",
"Will Saunders",
"Leroy Robison",
"Marvin Galloway",
"Marco Goodwin",
"Jack Moor",
"Wendell Walls",
"Maurice Oneill",
"Merle Burnett",
"Cory Pearce",
"Kurt Cowan",
"Charlie Craig",
]

count = input("How many names would you like? i recommend no more than 20 at once: ")

countnum = int(count)

for x in range(countnum):
	print(random.choice(choice))
